title: Chilitime Design
email: bowmanmc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chilitime Design - a human-centered data visualization design company in Dayton, Ohio.
baseurl: "https://www.chilitime.design"
url: "https://www.chilitime.design"
twitter_username: webslingerm
github_username:  bowmanmc
card: /images/chilitime-card-1200.png

sass:
    load_paths:
      - _sass
      - node_modules
    style: compressed

# Build settings
permalink: /:year/:month/:title/
future: true
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
